Update enable func
SUSE-Enceladus/ahb-extension pull request #2
Opened 2022-03-21 12:00 UTC by jesusbv

2022-03-21 12:14 UTC, jesusbv commented
PR #1 should be merged first

2022-03-24 17:43 UTC, rjschwei requested changes

2022-03-24 17:43 UTC, rjschwei commented on main/ahb_for_sles.go
> +    RegionSrvEnablerService: "regionsrv-enabler-azure.service",
We need to enable the timer, not the service, i.e. s/service/timer/

2022-03-24 17:52 UTC, rjschwei commented
#3 contains everything

2022-03-24 17:52 UTC, closed without merging